trigger:
- feat/hugo-build

resources:
  repositories:
  - repository: NewHugoWebsite
    type: github
    endpoint: coderdojo-linz
    name: coderdojo-linz/preview-coderdojo-linz.github.io

pool:
  vmImage: 'ubuntu-latest'

variables:
  hugo_version: '0.71.1'
  target_repository: 'https://github.com/coderdojo-linz/preview-coderdojo-linz.github.io.git'

steps:
- checkout: self
  persistCredentials: true
  clean: true
  path: src
  displayName: 'Checkout source'

- checkout: NewHugoWebsite
  persistCredentials: true
  clean: true
  path: dest
  displayName: 'Checkout destination'

- script: |
    git config --global user.email "rainer@software-architects.at"
    git config --global user.name "Rainer"
  displayName: 'Git Settings'

- script:
    pwd
    ls -la
    ls ./src -la
    ls ./dest -la
  displayName: Directory list

- script: |
    wget https://github.com/gohugoio/hugo/releases/download/v$(hugo_version)/hugo_$(hugo_version)_Linux-64bit.deb \
        -O '$(Pipeline.Workspace)/hugo_$(hugo_version)_Linux-64bit.deb'
    sudo dpkg -i $(Pipeline.Workspace)/hugo*.deb
  condition: False
  displayName: 'Install Hugo'

- script: |
    cd ./src
    hugo
  condition: False
  displayName: 'Build'

- task: CopyFiles@2
  inputs:
    sourceFolder: src/public
    targetFolder: $(Agent.TempDirectory)/public
    cleanTargetFolder: true
    overWrite: true
  condition: False
  displayName: 'Copy build result to temp'
