trigger:
- feat/hugo-build

resources:
  repositories:
  - repository: NewHugoWebsite
    type: github
    endpoint: coderdojo-linz
    name: coderdojo-linz/preview-coderdojo-linz.github.io

pool:
  vmImage: 'ubuntu-latest'

variables:
  hugo_version: '0.71.1'
  target_repository: 'https://github.com/coderdojo-linz/preview-coderdojo-linz.github.io.git'

steps:
- checkout: self
  persistCredentials: true
  clean: true
  path: src
  displayName: 'Checkout source'

- checkout: NewHugoWebsite
  persistCredentials: true
  clean: true
  path: dest
  displayName: 'Checkout destination'

- script: |
    git config --global user.email "rainer@software-architects.at"
    git config --global user.name "Rainer"
  displayName: 'Git Settings'

- script: |
    wget https://github.com/gohugoio/hugo/releases/download/v$(hugo_version)/hugo_extended_$(hugo_version)_Linux-64bit.deb \
        -O '$(Pipeline.Workspace)/hugo_$(hugo_version)_Linux-64bit.deb'
    sudo dpkg -i $(Pipeline.Workspace)/hugo*.deb
  displayName: 'Install Hugo'

- script: |
    npm install
  workingDirectory: $(Agent.BuildDirectory)/src
  displayName: 'Run npm install'

- script: |
    hugo
  workingDirectory: $(Agent.BuildDirectory)/src
  displayName: 'Build'

- task: CopyFiles@2
  inputs:
    sourceFolder: $(Agent.BuildDirectory)/src/public
    targetFolder: $(Agent.BuildDirectory)/dest
    cleanTargetFolder: true
    overWrite: true
  displayName: 'Copy build result to destination'
  
- script: |
    echo -e linz-preview.coderdojo.net'\n' > CNAME
  workingDirectory: $(Agent.BuildDirectory)/dest
  displayName: 'Create CNAME file for GitHub Pages'

- script: |
    git clone git@github.com:coderdojo-linz/preview-coderdojo-linz.github.io.git
    cd preview-coderdojo-linz
    echo -e linz-preview.coderdojo.net'\n' > CNAME
    git add --all .
    git commit -m 'Update website'
    git push origin master
  workingDirectory: $(Agent.BuildDirectory)
  displayName: 'Git push '

- script: |
    pwd
    ls -la
    git add --all .
    git commit -m 'Update website'
    git push origin master
  condition: False
  workingDirectory: $(Agent.BuildDirectory)/dest
  displayName: 'Git push '